const ActionTypes = {
  REQ_GET_LOGIN: "REQ_GET_LOGIN",
  GET_LOGIN_RESPONSE: "GET_LOGIN_RESPONSE",
  CHECK_AUTH: "CHECK_AUTH",
  CHECK_AUTH_RESPONSE: "CHECK_AUTH_RESPONSE",

  UPDATE_USER: "UPDATE_USER",
  UPDATE_USER_RESPONSE: "UPDATE_USER_RESPONSE",
  GET_USERS_RESPONSE: "GET_USERS_RESPONSE",
  REQ_GET_USERS: "REQ_GET_USERS",
  REQ_GET_USERS_PAGINATION: "REQ_GET_USERS_PAGINATION",
  ADD_USER: "ADD_USER",
  ADD_USER_RESPONSE: "ADD_USER_RESPONSE",
  DEL_USER: "DEL_USER",
  DEL_USER_RESPONSE: "DEL_USER_RESPONSE",

  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  UPDATE_PRODUCT_RESPONSE: "UPDATE_PRODUCT_RESPONSE",
  REQ_GET_PRODUCTS: "REQ_GET_PRODUCTS",
  GET_PRODUCTS_RESPONSE: "GET_PRODUCTS_RESPONSE",
  ADD_PRODUCT: "ADD_PRODUCT",
  ADD_PRODUCT_RESPONSE: "ADD_PRODUCT_RESPONSE",
  DEL_PRODUCT: "DEL_PRODUCT",
  DEL_PRODUCT_RESPONSE: "DEL_PRODUCT_RESPONSE",
};

export default ActionTypes;
